spring.security.user.name=disabled
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:disabled}
frontend.url=${FRONTEND_URL:http://localhost:4200}
logging.level.root=DEBUG

server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:false}
