name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo (optional here)
      - name: Checkout repo
        uses: actions/checkout@v4


      # 3. Deploy on EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            echo "Logging into GHCR on EC2..."
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

            echo "Moving to app folder..."
            cd /opt/app

            echo "Pulling latest images..."
            docker compose pull

            echo "Restarting containers..."
            docker compose up -d --remove-orphans

            echo "Deployment done"
