name: Deploy + Expose via Ngrok

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Load repo into GitHub runner (IMPORTANT)
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Debug repo structure (now it will show files)

      # 3. Connect to Tailscale network
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Prepare folder on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir C:\deploy
      # 4. Copy docker-compose.yml to server
      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yaml"
          target: "C:/deploy"

      # 5. Deploy + start ngrok
      - name: SSH deploy + ngrok
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd C:/deploy

            echo "🚀 Starting containers..."
            docker compose up -d

            echo "🌐 Starting ngrok..."
            start /B ngrok http 80

            timeout /t 5 > nul

            echo "🔍 ngrok URL:"
            curl -s http://127.0.0.1:4040/api/tunnels
